# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - swagger generate client -t ./generated-client -f https://api.radix.equinor.com/swaggerui/swagger.json -A radixapi
builds:
  - binary: rx
    env:
      - CGO_ENABLED=0
    goos:
      - linux
dockers:
  - image_templates:
      - "docker.pkg.github.com/equinor/radix-cli/rx:latest"
    dockerfile: Dockerfile
    binaries:
      - rx
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
